[package]
name = "universal-weave"
version = "0.0.0"
authors = [
	"transkatgirl",
]
license = "Unlicense"
description = "A flexible data format intended for \"loom\" implementations."
edition = "2024"

[features]
default = [ "rkyv" ]
rkyv = [
	"dep:rkyv",
]
legacy = [  ]
serde = [
	"dep:serde",
	"indexmap/serde",
]

[dependencies]
contracts = "0.6.7"
indexmap = "2.13.0"
rkyv = { version = "0.8.14", features = [
	"little_endian",
	"aligned",
	"pointer_width_32",
	"indexmap-2",
], optional = true }
serde = { version = "1.0.228", features = [
	"derive",
], optional = true }
