[package]
name = "loomkit"
version = "0.1.0"
authors = [
	"transkatgirl",
]
license = "Unlicense"
description = "A library for building loom-like data structures."
edition = "2024"

[dependencies]
contracts = "0.6.7"
rkyv = { version = "0.8.12", features = [
	"little_endian",
	"aligned",
	"pointer_width_32",
] }
rkyv_dyn = "0.7.44"
