[package]
name = "universal-weave"
version = "0.1.0"
authors = [
	"transkatgirl",
]
license = "Unlicense"
description = "A flexible data format intended for \"loom\" implementations."
edition = "2024"

[features]
serde = [
	"dep:serde",
	"indexmap/serde",
]

[dependencies]
contracts = "0.6.7"
indexmap = "2.12.1"
rkyv = { version = "0.8.12", features = [
	"little_endian",
	"aligned",
	"pointer_width_32",
	"indexmap-2",
] }
serde = { version = "1.0.228", features = [
	"derive",
], optional = true }

[workspace]
members = [
	"tapestry-weave",
]
